# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

install:
  Rscript -e 'devtools::install_github(c("r-lib/rlang@v0.3.0"), build_vignettes = FALSE, force = TRUE)'

matrix:
  include:
    - r: 3.1
      warnings_are_errors: false
    - r: 3.2
      warnings_are_errors: false
    - r: 3.3
      warnings_are_errors: false
    - r: 3.4
      warnings_are_errors: false
    - r: 3.5
      warnings_are_errors: false
      after_success:
        - Rscript -e 'covr::codecov()'
    - r: devel
      warnings_are_errors: false
  allow_failures:
    - r: devel
